### ISSUE TITLE
ask help for model training and testing

### ISSUE THREAD

**Issue by BinFengPKU** [drewnutt/DDG#1]
Thank you for your nice work, but I don't know how to construct the cache dir that contain all data file necessary for training, and I also don't know your argument setting for training. can you be so nice to help me? by the way, can you tell me how to run finetuneing and testing on external dataset?

**Comment by drewnutt** [comment]
- In order to construct a new cache file you need all of the raw data files (i.e. `pdb`s and `sdf`s) and a types file (that associates labels with the paths to the raw files). First the raw files need to be converted to gninatypes files; this is done with `gninatyper` which is installed with [gnina](https://github.com/gnina/gnina). Then you can use [create_caches2.py](https://github.com/gnina/scripts/blob/master/create_caches2.py) from the GNINA repo to create the molcache files, one for the receptors and one for the ligands.

- To run training with the hyperparameters used in the paper:
```
python3 python_files/ddg_reg_ptrain_siamese.py --ligtr <ligand training molcache file> --rectr <receptor training molcache file> --trainfile <train types file> --ligte <ligand testing molcache file> --recte <receptor testing molcache file>  --testfile <test types file> --lr 0.000367 --epoch 1000 --use_model multtask_latent_def2018 --batch_size 64 --hidden_size 0 --ddg_loss_weight 10
```

- Finally, to run finetuning you must first use `select_subset.py` to combine the initial training dataset with the new finetuning dataset as follows:
```
python3 python_files/select_subset.py -T <initial training dataset types file> -E <finetuning dataset types file> -N <number of test ligands to use during finetuning> --stratify
```
This will overwrite `<initial training dataset types file>` with a new types file that has a new column for stratification during training and new columns that have information from the finetuning dataset.
Then you can run the training on this dataset as follows:
```
python3 python_files/ddg_reg_ptrain_siamese.py --ligtr <ligand training molcache file> --rectr <receptor training molcache file> --trainfile <train types file> --ligte <ligand testing molcache file> --recte <receptor testing molcache file>  --batch_size 64 --lr 0.000367 --epoch 3 --use_model multtask_latent_def2018 --hidden_size 0 --ddg_loss_weight 10 --use_weights <weights of model trained on initial training dataset> --stratify --train_dataroot <root of directory containing gninatypes files of finetune inputs>
```

**Comment by tkram01** [comment]
Thanks for the additional info. I am 99% able to follow them but am running into an issue when using stratify. Any ideas on where to look?

```
python3 python_files/ddg_reg_ptrain_siamese.py --ligtr BindingDB_data/lig.molcache2  --rectr BindingDB_data/rec.molcache2 --trainfile BindingDB_data/all_data_train_papersplit_rand0_p_6.types --ligte BindingDB_data/lig_test.molcache2  --recte BindingDB_data/rec_test.molcache2   --batch_size 64 --lr 0.000367 --epoch 5 --use_model multtask_latent_def2018 --hidden_size 0 --ddg_loss_weight 10 --use_weights model-base.h5 --no_wandb --testfile BindingDB_data/all_data_test_papersplit_rand0_p_6.types --stratify 

27648
GPUS: 1
done moving model
applied weights
about to use weights
training now
Traceback (most recent call last):
  File "/home/ubuntu/DDG/python_files/ddg_reg_ptrain_siamese.py", line 496, in <module>
    tt_loss, out_d, tt_r, tt_rmse, tt_mae, tt_act = test(model, teste, latent_rep,1,proj=projector)
  File "/home/ubuntu/DDG/python_files/ddg_reg_ptrain_siamese.py", line 307, in test
    loss = args.absolute_loss_weight * (loss_lig1 + loss_lig2) + args.ddg_loss_weight * ddg_loss + args.rotation_loss_weight[it] * rotation_loss + args.consistency_loss_weight * nn.functional.mse_loss((lig1-lig2),output)
IndexError: index 10 is out of bounds for axis 0 with size 10
```

**Comment by drewnutt** [comment]
I ran the exact same command and did not get this error. Do you get the same error even without `--stratify`?

What version of pytorch and libmolgrid are you using?

**Comment by tkram01** [comment]
I don't get an error if I don't use --stratify

torch==1.13.1
molgrid==0.5.2

**Comment by tkram01** [comment]
I've tried various versions of torch and molgrid. All lead to the same error.

**Comment by drewnutt** [comment]
Have you modified the test file you are providing (`BindingDB_data/all_data_test_papersplit_rand0_p_6.types`) from what is in the repo?

I am unable to reproduce this error on my side. I have pushed an update to `python_files/ddg_reg_ptrain_siamese.py` to remove the rotation loss warmup (that was never used in the paper), this should hopefully remove any possibility of the IndexError happening again.

**Comment by yyou1996** [comment]
I am pretty new to the data preprocessing. Might I know your scripts for using `create_cache2.py`? Specifically, I see there is an argument of the column here to separate ligands and receptors https://github.com/gnina/scripts/blob/53ad4d6e5578f54a29d92affce50a70b449600a6/create_caches2.py#L103 but I don't know how it is determined.
